name: Check OpenRTP Installer
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  openrtp:
    strategy:
    # java has little difference among environments, so fail-fast works effective.
      fail-fast: true
      matrix:
        platform: [ubuntu-20.04, ubuntu-18.04, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          lfs: false
        
      - name: Build & Install OpenRTP
        run: |
          cd externals/
          ./install_RTP.sh
