name: Check OpenRTP Installer
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  openrtp:
    timeout-minutes: 15
    strategy:
    # java has little difference among environments, so fail-fast works effective.
      fail-fast: true
      matrix:
        platform: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ${{ matrix.platform }}
    defaults:
      run:
        working-directory: hlab-nxo-setup
    
    steps:
      - name: Clone
        run: |
          cd ..
          git clone https://github.com/kazuki0824/hlab-nxo-setup.git hlab-nxo-setup --recurse-submodules

      - name: Build & Install OpenRTP
        run: |
          cd externals/
          ./install_RTP.sh
